AWSTemplateFormatVersion: "2010-09-09"
Description: "This stack it represents all platform components for this project"
Parameters:
  DeployEnvironment:
    Type: String
    AllowedValues: [Production, Labs]
  SubnetIds:
    Type: String
  CommonDataAccessSecurityGroupId:
    Type: String

Mappings:
  Labs:
    S3:
      BucketCloudFormation: xmens-cloudformation-architecture
    MutantApi:
      Stage: v1
    Redis:
      Port: 6379
      Nodes: 1
      ReplicasPerNodeGroup: 1
      ClusterName: xmens-elasticache-rediscl-labs
      ReplicationGroupClusterName: xmens-elasticache-gcl-labs
      NodeType: cache.t3.medium
      AutomaticFailoverEnabled: false
      PreferredMaintenanceWindow: sun:09:00-sun:10:00
      EngineName: redis
      EngineVersion: 5.0.6
      SubnetGroupName: xmens-conexion-subnetgroup
    Dynamodb:
      TableDnaName: dna
      TableStatName: stat
  Production:
    S3:
      BucketCloudFormation: xmens-cloudformation-architecture-prd
    MutantApi:
      Stage: v1
    Redis:
      Port: 6379
      Nodes: 1
      ReplicasPerNodeGroup: 1
      ClusterName: xmens-elasticache-rediscl-labs
      ReplicationGroupClusterName: xmens-elasticache-gcl-labs
      NodeType: cache.t3.medium
      AutomaticFailoverEnabled: false
      PreferredMaintenanceWindow: sun:09:00-sun:10:00
      EngineName: redis
      EngineVersion: 5.0.6
      SubnetGroupName: xmens-conexion-subnetgroup
    Dynamodb:
      TableDnaName: dna
      TableStatName: stat

Resources:
  RedisStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketCloudFormation}.s3.amazonaws.com/Redis/Redis.yml
        - {
            BucketCloudFormation:
              !FindInMap [!Ref DeployEnvironment, S3, BucketCloudFormation],
          }
      Parameters:
        RedisName: !FindInMap [!Ref DeployEnvironment, Redis, ClusterName]
        CommonDataAccessSecurityGroupId: !Ref CommonDataAccessSecurityGroupId
        RedisNodes: !FindInMap [!Ref DeployEnvironment, Redis, Nodes]
        RedisNodeType: !FindInMap [!Ref DeployEnvironment, Redis, NodeType]
        RedisEngineName: !FindInMap [!Ref DeployEnvironment, Redis, EngineName]
        RedisEngineVersion:
          !FindInMap [!Ref DeployEnvironment, Redis, EngineVersion]
        RedisPreferredMaintenanceWindow:
          !FindInMap [!Ref DeployEnvironment, Redis, PreferredMaintenanceWindow]
        RedisPort: !FindInMap [!Ref DeployEnvironment, Redis, Port]
        Stage: !Ref DeployEnvironment
        RedisSubnetGroupName:
          !FindInMap [!Ref DeployEnvironment, Redis, SubnetGroupName]
        SubnetsIds: !Ref SubnetIds

  MutantApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketCloudFormation}.s3.amazonaws.com/MutantApi/MutantApi.yml
        - {
            BucketCloudFormation:
              !FindInMap [!Ref DeployEnvironment, S3, BucketCloudFormation],
          }
      Parameters:
        DeployEnvironment: !Ref DeployEnvironment
        SubnetPrivate: !Ref SubnetIds
        CommonDataAccessSecurityGroupId: !Ref CommonDataAccessSecurityGroupId
        HostRedis: !GetAtt RedisStack.Outputs.Address
        PortRedis: !FindInMap [!Ref DeployEnvironment, Redis, Port]
        DynamoDbTableDna:
          !FindInMap [!Ref DeployEnvironment, Dynamodb, TableDnaName]
        DynamoDbTableStat:
          !FindInMap [!Ref DeployEnvironment, Dynamodb, TableStatName]

  DynamodbStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - https://${BucketCloudFormation}.s3.amazonaws.com/dynamodb/dynamodb.yml
        - {
            BucketCloudFormation:
              !FindInMap [!Ref DeployEnvironment, S3, BucketCloudFormation],
          }
      Parameters:
        DeployEnvironment: !Ref DeployEnvironment
        DynamoDbTableDna:
          !FindInMap [!Ref DeployEnvironment, Dynamodb, TableDnaName]
        DynamoDbTableStat:
          !FindInMap [!Ref DeployEnvironment, Dynamodb, TableStatName]
