AWSTemplateFormatVersion: "2010-09-09"
Description: "This stacks represent all configuration for creation redis"
Parameters:
  RedisName:
    Type: "String"
  RedisNodes:
    Type: "Number"
  RedisNodeType:
    Type: "String"
  RedisEngineName:
    Type: "String"
  RedisEngineVersion:
    Type: "String"
  RedisPreferredMaintenanceWindow:
    Type: "String"
  RedisPort:
    Type: "Number"
  Stage:
    Type: "String"
  RedisSubnetGroupName:
    Type: "String"
  SubnetsIds:
    Type: "CommaDelimitedList"
  CommonDataAccessSecurityGroupId:
    Type: "String"
Resources:

  ConexionesRedisElastiCache:
    Type: AWS::ElastiCache::CacheCluster
    Properties:
      CacheNodeType: !Ref RedisNodeType
      ClusterName: !Ref RedisName
      Engine: !Ref RedisEngineName
      EngineVersion: !Ref RedisEngineVersion
      NumCacheNodes: !Ref RedisNodes
      Port: !Ref RedisPort
      CacheSubnetGroupName: !Ref RedisSubnetsGroup
      PreferredMaintenanceWindow: !Ref RedisPreferredMaintenanceWindow
      VpcSecurityGroupIds:
        - !Ref CommonDataAccessSecurityGroupId
      Tags:
        - Key: "Stage"
          Value: !Ref Stage
        - Key: "Area"
          Value: "Tecnologia"
        - Key: "Name"
          Value: !Ref RedisName
  RedisSubnetsGroup:
    Type: "AWS::ElastiCache::SubnetGroup"
    Properties:
      CacheSubnetGroupName: !Ref RedisSubnetGroupName
      Description: !Ref RedisSubnetGroupName
      SubnetIds: !Ref SubnetsIds

Outputs:
  Address:
    Value: !GetAtt ConexionesRedisElastiCache.RedisEndpoint.Address
